#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $SPGW_DB_NAME;
    CREATE USER "$SPGW_DB_USER" WITH PASSWORD '$SPGW_DB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $SPGW_DB_NAME TO "$SPGW_DB_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$SPGW_DB_NAME" <<-EOSQL
    GRANT ALL ON SCHEMA public TO "$SPGW_DB_USER";
    ALTER SCHEMA public OWNER TO "$SPGW_DB_USER";
EOSQL
